# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7a1fb07052bfc4dd27538e257a43bbdf1390aa62884d0f111592890594dce6deb0023fc3f48c153c2735a7c561d87b06b140a272bcc4cbe32e40de26ab05cac

test:
  secret_key_base: a9ec6da2dfa18aa0db67045b63a96740791109cfb6ba730c5b71bfc23745ea737f8461c36f26e6b8be7c8f4ea2d73e6e40a56e696fa66ce29e5eb9a124570956

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
